#pragma once

#include <QString>
#include <QStringList>
#include <QObject>
#include <QVector>
#include <array>
#include <cstdint>

#include "MorphOutputId.h"
#include "Footage.h"
#include "KeyboardStandardRanges.h"
#include "PiecewiseCurve.h"
#include "InstrumentDefinition.h"


enum class PlayMode : uint8_t { Poly, Mono };

//--------------------
struct TrackPresetData
//--------------------
{
  MorphOutputId morphOutput = MorphOutputId::None;

  Footage footage = Footage::ftg8;
  uint8_t program_cc0 = 0;
  uint8_t program_cc32 = 0;
  uint8_t program_number = 0;
  uint8_t volume = 100;
  int8_t  panorama = 0;
  uint8_t reverb = 40;
  uint8_t chorus = 0;
  int8_t  timbre1 = 0;
  int8_t  timbre2 = 0;

  // Additional per-track tuning in cents. The random component is
  // generated by MidiEngine according to the current play mode.
  int8_t  detuneOffset = 0;
  uint8_t detuneSpread = 0;
};

//------------------
struct MidiSetupData
//------------------
{
  QString midiInPort;
  QString midiOutPort;
  uint8_t midiInChannel = 0;

  // Protect the per-track preset setup from incoming MIDI automation.
  // When enabled, Volume, Pan, Expression, Reverb, Chorus, Tone and
  // Timbre Control Changes received on the source channel are ignored.
  bool filterPresetControlChanges = true;
};

//--------------------
struct AppInitSettings
//--------------------
{
  MidiSetupData midiSetup;
  PlayMode playMode = PlayMode::Mono;
  PatchPolicy patchPolicy = PatchPolicy::Manual;
  QString knownInstrumentName;
  KeyboardRangeId keyboardRangeId = KeyboardRangeId::Full;
  uint8_t pitchBendRange = 2;
  uint8_t morphOutputMuteMask = 0;
  uint8_t morphOutputSoloMask = 0;
};

//----------------------------
struct MorphOutputPresetData
//----------------------------
{
  QString name;
  bool customName = false;
};

//---------------
struct PresetData
//---------------
{
  QString name;
  QString notes;

  AppInitSettings appInitSettings;
  std::array<TrackPresetData, 16> tracks;
  std::array<MorphOutputPresetData, 8> morphOutputs;
  PiecewiseCurve keyCurve;
  PiecewiseCurve velCurve;
};

//----------------------------------
class PresetManager : public QObject
//----------------------------------
{
  Q_OBJECT

public:
  explicit PresetManager(QObject* parent = nullptr);

  const QVector<PresetData>& presets() const;
  QStringList presetNames() const;

  bool loadFromDisk();
  bool saveToDisk() const;

  bool savePreset(const PresetData& preset);   // crea o sovrascrive per nome
  bool removePreset(const QString& name);
  const PresetData* findPreset(const QString& name) const;
  bool contains(const QString& key) const;

signals:
  void presetsChanged();

private:
  QVector<PresetData> presets_;
};